# Generated by Django 3.1.7 on 2021-03-21 05:53

from django.db import migrations, models
import django.db.models.deletion
import esite.heimdall.models
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_snekcustomer"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("remaining_uses", models.PositiveIntegerField(default=10)),
                (
                    "activate_remaining_uses_date",
                    models.DateTimeField(default=esite.heimdall.models.fortnight_hence),
                ),
                (
                    "license_expire_date",
                    models.DateTimeField(default=esite.heimdall.models.one_year_hence),
                ),
                (
                    "owner",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heimdall_licenses",
                        to="user.snekcustomer",
                    ),
                ),
            ],
        ),
    ]
