# Generated by Django 3.1.7 on 2021-03-21 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heimdall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncHeimdallGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('introspection', models.JSONField()),
                ('bridge_drop_binary_name', models.CharField(max_length=255, null=True)),
                ('bridge_drop_binary', models.BinaryField(null=True)),
                ('bridge_drop_binary_saved', models.BooleanField(default=False)),
            ],
        ),
    ]
