# Generated by Django 3.1.6 on 2021-02-22 01:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("heimdall", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AsyncHeimdallGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("introspection", models.JSONField()),
                (
                    "bridge_drop_binary_name",
                    models.CharField(max_length=255, null=True),
                ),
                ("bridge_drop_binary", models.BinaryField(null=True)),
                ("bridge_drop_binary_saved", models.BooleanField(default=False)),
            ],
        )
    ]
