# Generated by Django 3.1.6 on 2021-02-18 20:05

from django.db import migrations
import esite.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNEKCustomer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.snekuser',),
            managers=[
                ('objects', esite.user.models.SNEKCustomerManager()),
            ],
        ),
    ]
